# Generated by Django 5.2.15 on 2026-06-09 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor pago')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='último pagamento')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='rentals.rental', verbose_name='locação')),
            ],
            options={
                'verbose_name': 'recebimento',
                'verbose_name_plural': 'recebimentos',
                'ordering': ('due_date',),
            },
        ),
    ]
