# Generated by Django 5.2.15 on 2026-06-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0002_customer_is_placeholder_customer_legacy_id_and_more'),
        ('rentals', '0003_rental_cancelled_at_rental_cancelled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('legacy_code', models.CharField(blank=True, max_length=20, verbose_name='código legado')),
            ],
            options={
                'verbose_name': 'conta caixa',
                'verbose_name_plural': 'contas caixa',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(verbose_name='data')),
                ('direction', models.CharField(choices=[('inflow', 'Entrada'), ('outflow', 'Saída')], max_length=10, verbose_name='direção')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('description', models.TextField(blank=True, verbose_name='histórico')),
                ('source', models.CharField(choices=[('payment', 'Pagamento'), ('manual', 'Manual'), ('import', 'Importação'), ('adjustment', 'Ajuste'), ('reversal', 'Estorno')], default='manual', max_length=20, verbose_name='origem')),
                ('legacy_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID legado')),
            ],
            options={
                'verbose_name': 'movimento financeiro',
                'verbose_name_plural': 'movimentos financeiros',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('payment_date', models.DateField(verbose_name='data do pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor pago')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='juros')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto')),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('card_debit', 'Débito'), ('card_credit', 'Crédito'), ('transfer', 'Transferência'), ('other', 'Outro')], default='cash', max_length=20, verbose_name='forma de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('legacy_movement_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID do movimento legado')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='é estorno')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ('payment_date', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='receivable',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID legado'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='legacy_notes',
            field=models.TextField(blank=True, verbose_name='notas de importação'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='legacy_source',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem legada'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['due_date'], name='rcv_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['balance'], name='rcv_balance_idx'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='billing.cashaccount', verbose_name='conta'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements', to='customers.customer', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='billing.receivable', verbose_name='recebimento'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_movements', to='rentals.rental', verbose_name='locação'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.receivable', verbose_name='recebimento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rentals.rental', verbose_name='locação'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reversed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='billing.payment', verbose_name='estornado por'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_registered', to=settings.AUTH_USER_MODEL, verbose_name='operador'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['date'], name='fmv_date_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['direction'], name='fmv_direction_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='pmt_date_idx'),
        ),
    ]
