# Generated by Django 5.2.15 on 2026-06-12 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_cashaccount_financialmovement_payment_and_more'),
        ('customers', '0003_customer_is_active'),
        ('rentals', '0005_alter_rental_pickup_date_alter_rental_return_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['source'], name='fmv_source_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['due_date', 'balance'], name='rcv_overdue_idx'),
        ),
    ]
