# Generated by Django 5.2.15 on 2026-07-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billing_report_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='baixado em'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='written_off_reason',
            field=models.TextField(blank=True, verbose_name='motivo da baixa'),
        ),
    ]
