# Generated by Django 5.2.15 on 2026-08-11 01:47

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_financialmovement_unique_payment'),
        ('customers', '0010_customer_cnpj_customer_cnpj_digits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('inflow', 'Entrada'), ('reversal', 'Estorno')], default='inflow', max_length=10, verbose_name='tipo')),
                ('received_on', models.DateField(verbose_name='data do recebimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor recebido')),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('card_debit', 'Débito'), ('card_credit', 'Crédito'), ('transfer', 'Transferência'), ('other', 'Outro')], default='cash', max_length=20, verbose_name='forma de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='chave de idempotência')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='hash do conteúdo')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='customers.customer', verbose_name='cliente')),
                ('financial_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='billing.financialmovement', verbose_name='movimento financeiro')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts_registered', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='billing.receipt', verbose_name='estorno de')),
            ],
            options={
                'verbose_name': 'recibo',
                'verbose_name_plural': 'recibos',
                'ordering': ('-received_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor em caixa')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor de principal')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de juros')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de desconto')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocation', to='billing.payment', verbose_name='pagamento')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.receipt', verbose_name='recibo')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_allocations', to='billing.receivable', verbose_name='título')),
            ],
            options={
                'verbose_name': 'alocação de recibo',
                'verbose_name_plural': 'alocações de recibo',
                'ordering': ('receipt', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'inflow'), ('reversal_of__isnull', True)), models.Q(('kind', 'reversal'), ('reversal_of__isnull', False)), _connector='OR'), name='receipt_kind_reversal_consistent'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount__gte', 0), ('principal_amount__gte', 0), ('interest_amount__gte', 0), ('discount_amount__gte', 0)), name='receipt_alloc_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.CheckConstraint(condition=models.Q(('cash_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('principal_amount'), '+', models.F('interest_amount')), '-', models.F('discount_amount')))), name='receipt_alloc_cash_composition'),
        ),
        migrations.AddConstraint(
            model_name='receiptallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'receivable'), name='receipt_alloc_unique_receivable'),
        ),
    ]
