# Generated by Django 5.2.15 on 2026-06-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action', models.CharField(max_length=100, verbose_name='ação')),
                ('model_name', models.CharField(max_length=100, verbose_name='modelo')),
                ('object_id', models.CharField(max_length=50, verbose_name='ID do objeto')),
                ('object_repr', models.CharField(max_length=200, verbose_name='representação')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ('-created_at',),
            },
        ),
    ]
