# Generated by Django 5.2.15 on 2026-06-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('pickup_date', models.DateField(verbose_name='data de retirada')),
                ('return_date', models.DateField(verbose_name='data de retorno')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total')),
                ('penalty_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='multa')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('picked_up', 'Retirado'), ('returned', 'Devolvido')], default='pending', max_length=20, verbose_name='situação')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'locação',
                'verbose_name_plural': 'locações',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_items', to='catalog.product', verbose_name='produto')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rental', verbose_name='locação')),
            ],
            options={
                'verbose_name': 'item da locação',
                'verbose_name_plural': 'itens da locação',
            },
        ),
    ]
