# Generated by Django 5.2.15 on 2026-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='proof_photo',
            field=models.BinaryField(blank=True, null=True, verbose_name='foto de comprovação'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='proof_photo_content_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='tipo da foto'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='proof_photo_filename',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome da foto'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='proof_photo_height',
            field=models.PositiveIntegerField(default=0, verbose_name='altura da foto'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='proof_photo_size',
            field=models.PositiveIntegerField(default=0, verbose_name='tamanho da foto'),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='proof_photo_width',
            field=models.PositiveIntegerField(default=0, verbose_name='largura da foto'),
        ),
    ]
