# Generated by Django 5.2.15 on 2026-06-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentalitem_proof_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelado em'),
        ),
        migrations.AddField(
            model_name='rental',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_rentals', to=settings.AUTH_USER_MODEL, verbose_name='cancelado por'),
        ),
        migrations.AddField(
            model_name='rental',
            name='cancelled_reason',
            field=models.TextField(blank=True, verbose_name='motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='rental',
            name='legacy_notes',
            field=models.TextField(blank=True, verbose_name='notas de importação'),
        ),
        migrations.AddField(
            model_name='rental',
            name='use_for',
            field=models.CharField(blank=True, max_length=200, verbose_name='usar em'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('picked_up', 'Retirado'), ('returned', 'Devolvido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='situação'),
        ),
    ]
