# Generated by Django 5.2.15 on 2026-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_r7_contract_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='pickup_date',
            field=models.DateField(db_index=True, verbose_name='data de retirada'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(db_index=True, verbose_name='data de retorno'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('picked_up', 'Retirado'), ('returned', 'Devolvido'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20, verbose_name='situação'),
        ),
    ]
