# Generated by Django 5.2.15 on 2026-07-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rentalitem_product_snapshot_remove_use_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cash_discount',
            field=models.BooleanField(default=False, verbose_name='desconto à vista (10%)'),
        ),
    ]
