# Generated by Django 5.2.15 on 2026-07-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_rental_cash_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cash_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo em reais. Preencha apenas um dos dois campos de desconto.', max_digits=10, null=True, verbose_name='desconto à vista (R$)'),
        ),
        migrations.AddField(
            model_name='rental',
            name='cash_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual customizado para esta locação. Em branco, usa o padrão de 10%.', max_digits=5, null=True, verbose_name='desconto à vista (%)'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='cash_discount',
            field=models.BooleanField(default=False, verbose_name='desconto à vista'),
        ),
    ]
