# Generated by Django 5.2.15 on 2026-08-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_rental_cash_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='wearer_name',
            field=models.CharField(blank=True, help_text='Preencha quando quem vai usar a peça não é o(a) locatário(a) (ex.: esposa loca o terno para o marido usar).', max_length=150, verbose_name='quem vai usar'),
        ),
    ]
