# Generated by Django 5.2.15 on 2026-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_rental_wearer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor único cobrado se a devolução atrasar, qualquer que seja o número de dias. Não é uma diária.', max_digits=10, verbose_name='multa por atraso'),
        ),
    ]
