# Generated by Django 5.2.15 on 2026-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0013_alter_rental_penalty_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='wearer_name',
            field=models.CharField(blank=True, help_text='Preencha quando quem vai usar esta peça não é o(a) locatário(a) (ex.: esposa loca o terno para o marido usar).', max_length=150, verbose_name='quem vai usar'),
        ),
    ]
