# Generated by Django 5.2.15 on 2026-08-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0014_rentalitem_wearer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='wearer_name',
        ),
    ]
