# Generated by Django 5.2.15 on 2026-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0016_rentalitem_wearer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quanto custa repor as peças desta locação, se forem perdidas ou danificadas. Sai impresso na cláusula 3 do contrato.', max_digits=10, verbose_name='valor de reposição'),
        ),
    ]
