# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0017_alter_rental_penalty_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cancellation_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor calculado na rescisão'),
        ),
        migrations.AddField(
            model_name='rental',
            name='cancellation_penalty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percentual aplicado na rescisão'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor importado do contrato antigo, preservado apenas para auditoria.', max_digits=10, verbose_name='valor de reposição legado'),
        ),
    ]
