# Generated by Django 5.2.15 on 2026-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0019_rental_financial_policy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='damage_penalty_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo, em reais, cobrado uma vez nesta locação em caso de dano, definido na hora do contrato (a exemplo do valor de cada peça, que também é definido na hora do contrato, não fixo no acervo). Em branco, usa o padrão da empresa.', max_digits=10, null=True, verbose_name='multa por dano (R$)'),
        ),
    ]
