"""Diagnose a BRcom Access export without touching the Django database.

Input is the JSONL/schema export generated by ``export_access.ps1``. Output is
written under the export directory, which is ignored by Git because it may
contain real operational data.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path


VERSION = '2026.06.12-r1'
DEFAULT_EXPORT_DIR = Path('var/legacy_export')
DEFAULT_REPORT_DIR = Path('var/legacy_export/diagnostics')
DEFAULT_LEGACY_DIR = Path('brcom')

REQUIRED_TABLES = (
    'categoria',
    'clientes',
    'empresa',
    'libera',
    'locado',
    'movimento',
    'pagar',
    'produtos',
    'programas',
    'usuario',
)

DATE_FIELDS = {
    'locado': ('retirada', 'dev_prevista', 'dev_efetiva', 'data'),
    'movimento': ('data',),
    'pagar': ('vencimento', 'ult_pagto'),
    'temp': ('retirada', 'dev_prevista', 'dev_efetiva', 'data'),
}

REPORT_HINTS = {
    'locacao': ('contrato de locacao', 'contrato', 'temp.locação', 'venc1'),
    'locados': ('produtos a retirar/retirados', 'locado.retirada', 'RETIRA'),
    'receber': ('contas a receber por vencimento', '{pagar.pago} = 1'),
    'receberc': ('contas a receber por cliente', '{pagar.pago} = 1'),
    'vendas': ('locacoes realizadas', '{locado.retirado} = 1'),
}

TARGET_REPORTS = {
    'contrato de locacao': 'reports.contract',
    'produtos a retirar/retirados': 'reports.rented_items',
    'contas a receber por vencimento': 'billing.receivables_by_due_date',
    'contas a receber por cliente': 'billing.receivables_by_customer',
    'locacoes realizadas': 'reports.completed_rentals',
}


def read_json(path: Path):
    with path.open(encoding='utf-8-sig') as handle:
        return json.load(handle)


def read_jsonl(path: Path):
    rows = []
    with path.open(encoding='utf-8-sig') as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f'Invalid JSONL at {path}:{line_number}: {exc}') from exc
    return rows


def as_int(value):
    if value in (None, ''):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def as_decimal(value):
    if value in (None, ''):
        return Decimal('0')
    try:
        return Decimal(str(value)).quantize(Decimal('0.01'))
    except (InvalidOperation, ValueError):
        return Decimal('0')


def as_bool(value):
    if value in (None, ''):
        return False
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float, Decimal)):
        return value != 0
    return str(value).strip().lower() in {'1', '-1', 'true', 'yes', 'sim'}


def as_prefix(value):
    return str(value or '').strip().upper()


def as_date(value):
    if value in (None, ''):
        return None
    text = str(value).strip()
    for fmt in ('%Y-%m-%dT%H:%M:%S', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d'):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue
    return 'invalid'


def sum_decimal(rows, field):
    total = Decimal('0')
    for row in rows:
        total += as_decimal(row.get(field))
    return total


def money(value):
    return f'{value:.2f}'


def markdown_table(headers, rows):
    lines = [
        '| ' + ' | '.join(headers) + ' |',
        '| ' + ' | '.join('---' for _ in headers) + ' |',
    ]
    for row in rows:
        lines.append('| ' + ' | '.join(str(cell) for cell in row) + ' |')
    return '\n'.join(lines)


def count_by(rows, *fields):
    counter = Counter()
    for row in rows:
        key = tuple(row.get(field) for field in fields)
        counter[key] += 1
    return counter


def date_diagnostics(tables):
    result = {}
    for table_name, fields in DATE_FIELDS.items():
        if table_name not in tables:
            continue
        table_result = {}
        for field in fields:
            buckets = Counter()
            for row in tables[table_name]:
                parsed = as_date(row.get(field))
                if parsed is None:
                    buckets['null'] += 1
                elif parsed == 'invalid':
                    buckets['invalid'] += 1
                elif parsed.year < 1900:
                    buckets['before_1900'] += 1
                elif parsed.year > 2035:
                    buckets['after_2035'] += 1
                else:
                    buckets['ok'] += 1
            table_result[field] = dict(sorted(buckets.items()))
        result[table_name] = table_result
    return result


def schema_summary(export_dir, tables):
    rows = []
    for table_name in sorted(tables):
        schema = read_json(export_dir / 'schema' / f'{table_name}.json')
        columns = schema.get('columns', [])
        rows.append({
            'table': table_name,
            'rows': len(tables[table_name]),
            'columns': len(columns),
            'fields': [
                {
                    'name': column.get('name'),
                    'data_type': column.get('data_type'),
                    'max_length': column.get('max_length'),
                }
                for column in columns
            ],
        })
    return rows


def orphan_diagnostics(tables):
    clientes_ids = {as_int(row.get('numero')) for row in tables['clientes']}
    clientes_ids.discard(None)

    produtos_keys = {
        (as_prefix(row.get('prefixo')), as_int(row.get('codigo')))
        for row in tables['produtos']
    }
    produtos_keys.discard(('', None))

    locacao_numbers = {as_int(row.get('locação')) for row in tables['locado']}
    locacao_numbers.discard(None)

    pagar_ids = {as_int(row.get('id')) for row in tables['pagar']}
    pagar_ids.discard(None)

    locado_client_orphans = [
        row for row in tables['locado'] if as_int(row.get('cliente')) not in clientes_ids
    ]
    locado_product_orphans = [
        row
        for row in tables['locado']
        if (as_prefix(row.get('prefixo')), as_int(row.get('codigo'))) not in produtos_keys
    ]
    pagar_client_orphans = [
        row for row in tables['pagar'] if as_int(row.get('cliente')) not in clientes_ids
    ]
    pagar_locacao_orphans = [
        row for row in tables['pagar'] if as_int(row.get('locação')) not in locacao_numbers
    ]
    movimento_client_orphans = [
        row
        for row in tables['movimento']
        if as_int(row.get('cliente')) is not None
        and as_int(row.get('cliente')) not in clientes_ids
    ]
    movimento_partida_matches = [
        row
        for row in tables['movimento']
        if as_int(row.get('partida')) in pagar_ids
    ]

    return {
        'locado_client_orphans': len(locado_client_orphans),
        'locado_product_orphans': len(locado_product_orphans),
        'locado_product_orphan_distinct_keys': len({
            (as_prefix(row.get('prefixo')), as_int(row.get('codigo')))
            for row in locado_product_orphans
        }),
        'pagar_client_orphans': len(pagar_client_orphans),
        'pagar_locacao_orphans': len(pagar_locacao_orphans),
        'pagar_locacao_orphan_distinct_numbers': len({
            as_int(row.get('locação')) for row in pagar_locacao_orphans
        }),
        'movimento_client_orphans': len(movimento_client_orphans),
        'movimento_partida_matches_pagar': len(movimento_partida_matches),
    }


def duplicate_product_diagnostics(tables):
    grouped = defaultdict(list)
    for row in tables['produtos']:
        key = (as_prefix(row.get('prefixo')), as_int(row.get('codigo')))
        grouped[key].append(as_int(row.get('id')))
    duplicates = {
        f'{prefix}{code}': ids
        for (prefix, code), ids in sorted(grouped.items())
        if prefix and code is not None and len(ids) > 1
    }
    return {
        'groups': len(duplicates),
        'items': sum(len(ids) for ids in duplicates.values()),
        'top': [
            {'key': key, 'count': len(ids), 'ids': ids[:10]}
            for key, ids in list(duplicates.items())[:50]
        ],
    }


def missing_prefix_diagnostics(tables):
    category_prefixes = {as_prefix(row.get('prefixo')) for row in tables['categoria']}
    category_prefixes.discard('')

    result = {}
    for table_name in ('produtos', 'locado'):
        grouped = Counter()
        for row in tables[table_name]:
            prefix = as_prefix(row.get('prefixo'))
            if prefix and prefix not in category_prefixes:
                grouped[prefix] += 1
        result[table_name] = dict(sorted(grouped.items()))
    return result


def finance_diagnostics(tables):
    pagar_by_status = {}
    for (status,), count in count_by(tables['pagar'], 'pago').items():
        rows = [row for row in tables['pagar'] if row.get('pago') == status]
        amount = sum_decimal(rows, 'valor')
        paid = sum_decimal(rows, 'valor_pago')
        pagar_by_status[str(status)] = {
            'count': count,
            'amount': money(amount),
            'paid': money(paid),
            'balance': money(amount - paid),
        }

    payment_buckets = Counter()
    for row in tables['pagar']:
        amount = as_decimal(row.get('valor'))
        paid = as_decimal(row.get('valor_pago'))
        if paid == 0:
            bucket = 'zero'
        elif paid < amount:
            bucket = 'partial'
        elif paid == amount:
            bucket = 'exact'
        else:
            bucket = 'over'
        payment_buckets[(str(row.get('pago')), bucket)] += 1

    movimento_by_direction = {}
    for (direction,), count in count_by(tables['movimento'], 'es').items():
        rows = [row for row in tables['movimento'] if row.get('es') == direction]
        movimento_by_direction[str(direction)] = {
            'count': count,
            'amount': money(sum_decimal(rows, 'valor')),
        }

    movimento_by_account = {}
    for (account,), count in count_by(tables['movimento'], 'conta').items():
        rows = [row for row in tables['movimento'] if row.get('conta') == account]
        movimento_by_account[str(account)] = {
            'count': count,
            'amount': money(sum_decimal(rows, 'valor')),
        }

    return {
        'pagar_status_semantics': {
            '0': 'encerrado/quitado no legado',
            '1': 'aberto/a receber no legado',
        },
        'pagar_by_pago': pagar_by_status,
        'pagar_payment_buckets': {
            f'pago={status}:{bucket}': count
            for (status, bucket), count in sorted(payment_buckets.items())
        },
        'pagar_total_amount': money(sum_decimal(tables['pagar'], 'valor')),
        'pagar_total_paid': money(sum_decimal(tables['pagar'], 'valor_pago')),
        'pagar_total_balance': money(
            sum_decimal(tables['pagar'], 'valor') - sum_decimal(tables['pagar'], 'valor_pago')
        ),
        'movimento_by_direction': movimento_by_direction,
        'movimento_by_account': movimento_by_account,
        'movimento_total_amount': money(sum_decimal(tables['movimento'], 'valor')),
    }


def rental_diagnostics(tables):
    grouped = defaultdict(list)
    for row in tables['locado']:
        grouped[as_int(row.get('locação'))].append(row)
    item_buckets = Counter(len(rows) for rows in grouped.values())
    flags = Counter((row.get('devolvido'), row.get('retirado')) for row in tables['locado'])
    return {
        'distinct_rentals': len(grouped),
        'item_count_buckets': dict(sorted(item_buckets.items())),
        'flag_buckets': {
            f'devolvido={key[0]},retirado={key[1]}': value
            for key, value in sorted(flags.items())
        },
        'total_item_value': money(sum_decimal(tables['locado'], 'valor')),
        'total_penalty_value': money(sum_decimal(tables['locado'], 'multa')),
    }


def extract_strings(path, min_len=4):
    data = path.read_bytes()
    patterns = (
        (rb'[\x20-\x7E\x80-\xFF]{%d,}' % min_len, 'latin1'),
        ((rb'(?:[\x20-\x7E]\x00){%d,}' % min_len), 'utf-16le'),
    )
    strings = []
    for pattern, encoding in patterns:
        for match in re.finditer(pattern, data):
            text = match.group(0).decode(encoding, errors='ignore')
            text = re.sub(r'\s+', ' ', text).strip()
            if text:
                strings.append(text)
    return strings


def report_diagnostics(legacy_dir):
    reports = []
    if not legacy_dir.exists():
        return reports

    for path in sorted(legacy_dir.glob('*.rpt')):
        lower_name = path.name.lower()
        text_blob = '\n'.join(extract_strings(path))
        hints = []
        for name_fragment, values in REPORT_HINTS.items():
            if name_fragment in lower_name or any(value in text_blob for value in values[1:]):
                hints.append(values[0])
        targets = [
            TARGET_REPORTS[purpose]
            for purpose in dict.fromkeys(hints)
            if purpose in TARGET_REPORTS
        ]
        reports.append({
            'file': str(path),
            'size': path.stat().st_size,
            'purpose': '; '.join(dict.fromkeys(hints)) or 'unknown',
            'target': '; '.join(targets) or 'needs_manual_mapping',
            'mentions_pagar_open': '{pagar.pago} = 1' in text_blob,
            'mentions_locado_retirado': '{locado.retirado} = 1' in text_blob,
            'mentions_contract': 'CONTRATO DE LOCA' in text_blob.upper(),
        })
    return reports


def build_markdown(diagnostics):
    lines = [
        '# Diagnostico da Exportacao Legada BRcom',
        '',
        f"- Versao do diagnostico: `{diagnostics['diagnostic_version']}`",
        f"- Export dir: `{diagnostics['export_dir']}`",
        f"- Manifest exporter: `{diagnostics.get('manifest', {}).get('exporter_version', 'n/a')}`",
        '',
        '## Tabelas',
        '',
    ]
    table_rows = [
        [item['table'], item['rows'], item['columns']]
        for item in diagnostics['schema_summary']
    ]
    lines.append(markdown_table(['Tabela', 'Linhas', 'Colunas'], table_rows))
    lines.extend(['', '### Colunas por tabela', ''])
    for item in diagnostics['schema_summary']:
        lines.append(f"#### {item['table']}")
        lines.append(markdown_table(
            ['Coluna', 'Tipo Access', 'Tamanho'],
            [
                [field['name'], field['data_type'], field['max_length']]
                for field in item['fields']
            ],
        ))
        lines.append('')

    lines.extend(['', '## Orfaos e Vínculos', ''])
    lines.append(markdown_table(
        ['Indicador', 'Valor'],
        [[key, value] for key, value in diagnostics['orphans'].items()],
    ))

    lines.extend(['', '## Produtos Duplicados', ''])
    duplicates = diagnostics['duplicate_products']
    lines.append(f"- Grupos duplicados: {duplicates['groups']}")
    lines.append(f"- Itens em grupos duplicados: {duplicates['items']}")

    lines.extend(['', '## Prefixos sem Categoria', ''])
    for table_name, prefixes in diagnostics['missing_prefixes'].items():
        lines.append(f'### {table_name}')
        if prefixes:
            lines.append(markdown_table(['Prefixo', 'Linhas'], prefixes.items()))
        else:
            lines.append('Nenhum.')
        lines.append('')

    lines.extend(['## Datas Suspeitas', ''])
    for table_name, fields in diagnostics['dates'].items():
        lines.append(f'### {table_name}')
        rows = []
        for field, buckets in fields.items():
            for bucket, count in buckets.items():
                rows.append([field, bucket, count])
        lines.append(markdown_table(['Campo', 'Faixa', 'Linhas'], rows))
        lines.append('')

    lines.extend(['## Financeiro', ''])
    finance = diagnostics['finance']
    lines.append(f"- Total `pagar.valor`: {finance['pagar_total_amount']}")
    lines.append(f"- Total `pagar.valor_pago`: {finance['pagar_total_paid']}")
    lines.append(f"- Total saldo `pagar.valor - pagar.valor_pago`: {finance['pagar_total_balance']}")
    lines.append(f"- Total `movimento.valor`: {finance['movimento_total_amount']}")
    lines.append(f"- Movimentos com `partida` vinculada a `pagar.id`: {diagnostics['orphans']['movimento_partida_matches_pagar']}")
    lines.append('')
    lines.append('### Semantica de `pagar.pago`')
    lines.append(markdown_table(
        ['Valor', 'Significado'],
        finance['pagar_status_semantics'].items(),
    ))
    lines.append('')
    lines.append('### `pagar.pago`')
    lines.append(markdown_table(
        ['pago', 'Linhas', 'Valor', 'Valor pago', 'Saldo'],
        [
            [key, value['count'], value['amount'], value['paid'], value['balance']]
            for key, value in finance['pagar_by_pago'].items()
        ],
    ))
    lines.append('')
    lines.append('### Baldes de pagamento')
    lines.append(markdown_table(
        ['Balde', 'Linhas'],
        finance['pagar_payment_buckets'].items(),
    ))

    lines.extend(['', '## Locacoes', ''])
    rental = diagnostics['rentals']
    lines.append(f"- Locacoes distintas em `locado`: {rental['distinct_rentals']}")
    lines.append(f"- Soma `locado.valor`: {rental['total_item_value']}")
    lines.append(f"- Soma `locado.multa`: {rental['total_penalty_value']}")

    lines.extend(['', '## Relatorios Crystal', ''])
    report_rows = [
        [
            item['file'],
            item['size'],
            item['purpose'],
            item['target'],
            item['mentions_pagar_open'],
            item['mentions_locado_retirado'],
            item['mentions_contract'],
        ]
        for item in diagnostics['reports']
    ]
    lines.append(markdown_table(
        ['Arquivo', 'Bytes', 'Finalidade inferida', 'Relatorio alvo', 'pagar aberto', 'locado retirado', 'contrato'],
        report_rows,
    ))

    return '\n'.join(lines) + '\n'


def run(export_dir, report_dir, legacy_dir):
    manifest_path = export_dir / 'manifest.json'
    if not manifest_path.exists():
        raise FileNotFoundError(f'Manifest not found: {manifest_path}')

    manifest = read_json(manifest_path)
    tables = {}
    missing = []
    for table_name in REQUIRED_TABLES:
        path = export_dir / 'data' / f'{table_name}.jsonl'
        if path.exists():
            tables[table_name] = read_jsonl(path)
        else:
            missing.append(table_name)
    if missing:
        raise FileNotFoundError(f'Missing exported tables: {", ".join(missing)}')

    optional_temp = export_dir / 'data' / 'temp.jsonl'
    if optional_temp.exists():
        tables['temp'] = read_jsonl(optional_temp)

    diagnostics = {
        'diagnostic_version': VERSION,
        'export_dir': str(export_dir),
        'manifest': manifest,
        'schema_summary': schema_summary(export_dir, tables),
        'orphans': orphan_diagnostics(tables),
        'duplicate_products': duplicate_product_diagnostics(tables),
        'missing_prefixes': missing_prefix_diagnostics(tables),
        'dates': date_diagnostics(tables),
        'finance': finance_diagnostics(tables),
        'rentals': rental_diagnostics(tables),
        'reports': report_diagnostics(legacy_dir),
    }

    report_dir.mkdir(parents=True, exist_ok=True)
    json_path = report_dir / 'diagnostico_legado.json'
    md_path = report_dir / 'diagnostico_legado.md'
    json_path.write_text(
        json.dumps(diagnostics, ensure_ascii=False, indent=2),
        encoding='utf-8',
    )
    md_path.write_text(build_markdown(diagnostics), encoding='utf-8')
    return json_path, md_path


def main():
    parser = argparse.ArgumentParser(
        description='Diagnose BRcom JSONL export without mutating the database.',
    )
    parser.add_argument('--export-dir', type=Path, default=DEFAULT_EXPORT_DIR)
    parser.add_argument('--report-dir', type=Path, default=DEFAULT_REPORT_DIR)
    parser.add_argument('--legacy-dir', type=Path, default=DEFAULT_LEGACY_DIR)
    args = parser.parse_args()

    json_path, md_path = run(args.export_dir, args.report_dir, args.legacy_dir)
    print(f'Wrote {json_path}')
    print(f'Wrote {md_path}')


if __name__ == '__main__':
    main()
