# Generated by Django 5.2.15 on 2026-06-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('action_key', models.CharField(max_length=100, verbose_name='ação')),
                ('allowed', models.BooleanField(default=False, verbose_name='liberado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_permissions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'permissão de ação',
                'verbose_name_plural': 'permissões de ação',
                'unique_together': {('user', 'action_key')},
            },
        ),
    ]
