# Generated by Django 5.2.15 on 2026-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_accounts_user_email_ci_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'tentativa de login falha',
                'verbose_name_plural': 'tentativas de login falhas',
            },
        ),
    ]
