# Generated by Django 5.2.15 on 2026-06-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('pickup_date', models.DateField(verbose_name='data de retirada')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='rentals.rental', verbose_name='locação')),
            ],
            options={
                'verbose_name': 'retirada',
                'verbose_name_plural': 'retiradas',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('return_date', models.DateField(verbose_name='data de devolução')),
                ('days_late', models.PositiveIntegerField(default=0, verbose_name='dias de atraso')),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='multa aplicada')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_record', to='rentals.rental', verbose_name='locação')),
            ],
            options={
                'verbose_name': 'devolução',
                'verbose_name_plural': 'devoluções',
            },
        ),
    ]
