# Generated by Django 5.2.15 on 2026-06-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='pickup_date',
            field=models.DateField(db_index=True, verbose_name='data de retirada'),
        ),
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateField(db_index=True, verbose_name='data de devolução'),
        ),
    ]
