# Generated by Django 5.2.15 on 2026-08-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_alter_pickup_pickup_date_alter_return_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='damage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor cobrado por danos'),
        ),
        migrations.AddField(
            model_name='return',
            name='damage_notes',
            field=models.TextField(blank=True, verbose_name='observações sobre danos'),
        ),
    ]
