# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_return_damage_amount_return_damage_notes'),
        ('rentals', '0018_rental_cancellation_penalty_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='damage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percentual aplicado por dano'),
        ),
        migrations.AddField(
            model_name='return',
            name='damaged_items',
            field=models.ManyToManyField(blank=True, related_name='damage_return_records', to='rentals.rentalitem', verbose_name='peças danificadas'),
        ),
        migrations.AddField(
            model_name='return',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor cobrado por perda/não devolução'),
        ),
        migrations.AddField(
            model_name='return',
            name='loss_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percentual aplicado por perda/não devolução'),
        ),
        migrations.AddField(
            model_name='return',
            name='lost_items',
            field=models.ManyToManyField(blank=True, related_name='loss_return_records', to='rentals.rentalitem', verbose_name='peças não devolvidas'),
        ),
    ]
