# Generated by Django 5.2.15 on 2026-06-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('phone_home', models.CharField(blank=True, max_length=20, verbose_name='telefone residencial')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, verbose_name='celular')),
                ('phone_work', models.CharField(blank=True, max_length=20, verbose_name='telefone comercial')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('name',),
            },
        ),
    ]
