# Generated by Django 5.2.15 on 2026-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_placeholder',
            field=models.BooleanField(db_index=True, default=False, verbose_name='é placeholder'),
        ),
        migrations.AddField(
            model_name='customer',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID legado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='legacy_notes',
            field=models.TextField(blank=True, verbose_name='notas de importação'),
        ),
        migrations.AddField(
            model_name='customer',
            name='legacy_source',
            field=models.CharField(blank=True, max_length=50, verbose_name='origem legada'),
        ),
    ]
