# Generated by Django 5.2.15 on 2026-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_alternate_phone_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cnpj_digits',
            field=models.CharField(blank=True, db_index=True, max_length=18, verbose_name='CNPJ (só dígitos)'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cnpj_digits'], name='customer_cnpj_digits_idx'),
        ),
    ]
