# Generated by Django 5.2.15 on 2026-06-09 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('prefix', models.CharField(max_length=10, unique=True, verbose_name='prefixo')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('prefix',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('code', models.PositiveIntegerField(verbose_name='código')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='cor')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='tamanho')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('category__prefix', 'code'),
                'unique_together': {('category', 'code')},
            },
        ),
    ]
