# Generated by Django 5.2.15 on 2026-07-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='catalog_product_value_gte_0'),
        ),
    ]
