# Generated by Django 5.2.15 on 2026-06-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='nome')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('phones', models.CharField(blank=True, max_length=150, verbose_name='telefones')),
                ('last_rental_number', models.PositiveIntegerField(default=0, verbose_name='última locação')),
                ('daily_interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='juros ao dia (%)')),
                ('footer_message', models.CharField(blank=True, max_length=255, verbose_name='mensagem de rodapé')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresa',
            },
        ),
    ]
