# Generated by Django 5.2.15 on 2026-07-20 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_r6_financial_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_report_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número do WhatsApp (com DDI, ex: 5543999998888)'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_report_time',
            field=models.TimeField(default=datetime.time(7, 30), verbose_name='horário do envio diário'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_reports_enabled',
            field=models.BooleanField(default=False, verbose_name='enviar relatório diário por WhatsApp'),
        ),
    ]
