# Generated by Django 5.2.15 on 2026-07-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_whatsapp_report_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('daily_interest_rate__gte', 0)), name='company_daily_interest_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('late_fee_rate__gte', 0)), name='company_late_fee_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_interest_rate__gte', 0)), name='company_monthly_interest_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('damage_penalty_rate__gte', 0)), name='company_damage_penalty_rate_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('loss_penalty_rate__gte', 0)), name='company_loss_penalty_rate_gte_0'),
        ),
    ]
