# Generated by Django 5.2.15 on 2026-07-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_company_daily_interest_rate_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cancellation_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Percentual do valor total cobrado em caso de desistência ou rescisão do contrato.', max_digits=5, verbose_name='penalidade por desistência/rescisão (%)'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('cancellation_penalty_rate__gte', 0)), name='company_cancellation_penalty_rate_gte_0'),
        ),
    ]
