# Generated by Django 5.2.15 on 2026-07-30 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_cancellation_penalty_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cancellation_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Percentual do valor total cobrado em caso de desistência ou rescisão do contrato.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='penalidade por desistência/rescisão (%)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='loss_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentual do valor do item cobrado em caso de perda ou não devolução.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='penalidade por perda/não devolução (%)'),
        ),
    ]
