# Generated by Django 5.2.15 on 2026-07-31 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_cancellation_penalty_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='damage_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Percentual do valor do item cobrado em caso de dano.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='penalidade por dano (%)'),
        ),
    ]
