# Generated by Django 5.2.15 on 2026-08-02 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_damage_penalty_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='late_return_daily_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Percentual do valor total da locação cobrado por dia de atraso na devolução.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='multa por dia de atraso na devolução (%)'),
        ),
        migrations.AddField(
            model_name='company',
            name='late_return_max_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Após esse número de dias a devolução deixa de ser atraso e passa a ser tratada como não devolução, cobrada pela penalidade de perda.', verbose_name='dias de atraso cobrados'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('late_return_daily_rate__gte', 0)), name='company_late_return_daily_rate_gte_0'),
        ),
    ]
