# Generated by Django 5.2.15 on 2026-08-02 22:12

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def bump_default_cancellation_rate(apps, schema_editor):
    """Move rows still on the old 50% default up to the new 100% default.

    Rows a store already customized away from 50 are left untouched.
    """
    Company = apps.get_model('company', 'Company')
    Company.objects.filter(cancellation_penalty_rate=Decimal('50')).update(
        cancellation_penalty_rate=Decimal('100')
    )


def revert_bump(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    Company.objects.filter(cancellation_penalty_rate=Decimal('100')).update(
        cancellation_penalty_rate=Decimal('50')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_late_return_daily_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cancellation_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentual do valor total cobrado em caso de desistência ou rescisão do contrato.', max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='penalidade por desistência/rescisão (%)'),
        ),
        migrations.RunPython(bump_default_cancellation_rate, revert_bump),
    ]
