# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_cancellation_penalty_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cancellation_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentual do valor total cobrado em caso de desistência ou rescisão do contrato.', max_digits=5, verbose_name='penalidade por desistência/rescisão (%)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='damage_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Percentual do valor do item cobrado em caso de dano.', max_digits=5, verbose_name='penalidade por dano (%)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='late_return_daily_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Percentual do valor total da locação cobrado por dia de atraso na devolução.', max_digits=5, verbose_name='multa por dia de atraso na devolução (%)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='loss_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Percentual do valor do item cobrado em caso de perda ou não devolução.', max_digits=5, verbose_name='penalidade por perda/não devolução (%)'),
        ),
    ]
