"""
Django settings for noivas_cia project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util as _importlib_util
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('true', '1', 'yes', 'on')


def _env_int(name, default):
    value = os.environ.get(name)
    if value is None or value.strip() == '':
        return default
    return int(value)


def _env_list(name, default=''):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(',') if item.strip()]


DJANGO_ENV = os.environ.get('DJANGO_ENV', 'development').strip().lower()
DEBUG = _env_bool('DJANGO_DEBUG', DJANGO_ENV != 'production')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-noivas-cia'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false.'
        )
if not DEBUG and (
    SECRET_KEY.lower().startswith('changeme')
    or SECRET_KEY.startswith('django-insecure')
):
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be replaced with a strong secret in production.'
    )

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'DJANGO_ALLOWED_HOSTS is required when DJANGO_DEBUG is false.'
    )

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'core.apps.CoreConfig',
    'accounts',
    'website',
    'customers',
    'catalog',
    'company',
    'rentals',
    'movements',
    'billing',
    'reports',
    'maintenance',
    'notifications',
]

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

USER_CREATOR_EMAILS = [
    email.strip().lower()
    for email in os.environ.get('USER_CREATOR_EMAILS', '').split(',')
    if email.strip()
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noivas_cia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'noivas_cia.wsgi.application'

_DATABASE_URL = os.environ.get('DATABASE_URL')

if _DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('DATABASE_NAME', BASE_DIR / 'db.sqlite3'),
            'OPTIONS': {'timeout': 20},
        }
    }
else:
    raise ImproperlyConfigured(
        'DATABASE_URL is required when DJANGO_DEBUG is false.'
    )

BACKUP_ROOT = Path(os.environ.get('BACKUP_ROOT', BASE_DIR / 'var' / 'backups'))

# Evolution API (WhatsApp) — daily report notifications. Feature stays inert
# until all three are set and Company.whatsapp_reports_enabled is on.
EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', '').strip().rstrip('/')
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', '').strip()
EVOLUTION_INSTANCE = os.environ.get('EVOLUTION_INSTANCE', '').strip()

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'accounts.password_validation.AppUserAttributeSimilarityValidator',
    },
    {
        'NAME': 'accounts.password_validation.AppMinimumLengthValidator',
    },
    {
        'NAME': 'accounts.password_validation.AppCommonPasswordValidator',
    },
    {
        'NAME': 'accounts.password_validation.AppNumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles')

MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', False)
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    'Noivas & Cia <no-reply@tonicoimbra.com>',
)

CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS')
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
# Health checks and metrics use HTTP directly on the internal Swarm network.
# Without this exemption, HTTPS redirection targets port 443 in the app
# container, where there is no listener.
SECURE_REDIRECT_EXEMPT = [r'^healthz/$', r'^metrics$']
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = _env_bool('CSRF_COOKIE_HTTPONLY', False)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', False)

if _env_bool('DJANGO_TRUST_X_FORWARDED_PROTO', not DEBUG):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

USE_X_FORWARDED_HOST = _env_bool('DJANGO_USE_X_FORWARDED_HOST', False)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# ── Observability / metrics — django-prometheus (OPTIONAL stack) ──
# Enable only when the dependency is installed. Without it this is a no-op, so
# adding monitoring cannot break the existing production deployment.
try:
    import django_prometheus  # noqa: F401

    PROMETHEUS_ENABLED = True
except ImportError:
    PROMETHEUS_ENABLED = False

if PROMETHEUS_ENABLED:
    # django-prometheus publishes `django_http_...` without a namespace prefix.
    # Dashboards and alerts use those names directly.
    #
    # Prometheus scrapes /metrics through the task's internal IP, which is not
    # in ALLOWED_HOSTS. The middleware rewrites Host only for this route before
    # SecurityMiddleware and rejects requests forwarded by Traefik. The Before
    # middleware still wraps the entire stack.
    if 'noivas_cia.middleware.MetricsHostMiddleware' not in MIDDLEWARE:
        MIDDLEWARE = ['noivas_cia.middleware.MetricsHostMiddleware'] + MIDDLEWARE

    if 'django_prometheus' not in INSTALLED_APPS:
        INSTALLED_APPS = INSTALLED_APPS + ['django_prometheus']

    if 'django_prometheus.middleware.PrometheusBeforeMiddleware' not in MIDDLEWARE:
        MIDDLEWARE = (
            ['django_prometheus.middleware.PrometheusBeforeMiddleware']
            + MIDDLEWARE
            + ['django_prometheus.middleware.PrometheusAfterMiddleware']
        )

    # Preserve the current backend semantics while adding database metrics.
    _PROMETHEUS_DB_ENGINE_MAP = {
        'django.db.backends.postgresql': 'django_prometheus.db.backends.postgresql',
        'django.db.backends.postgresql_psycopg2': (
            'django_prometheus.db.backends.postgresql'
        ),
        'django.db.backends.sqlite3': 'django_prometheus.db.backends.sqlite3',
        'django.db.backends.mysql': 'django_prometheus.db.backends.mysql',
    }
    for _db_config in DATABASES.values():
        _engine = _db_config.get('ENGINE', '')
        _db_config['ENGINE'] = _PROMETHEUS_DB_ENGINE_MAP.get(_engine, _engine)


# -- Administrative MCP server (OPTIONAL) ---------------------------------
# Both imports are checked before touching INSTALLED_APPS. Therefore an image
# without the optional dependencies boots exactly as before and exposes no MCP
# route.
MCP_ENABLED = all(
    _importlib_util.find_spec(module_name) is not None
    for module_name in ('rest_framework', 'mcp_server')
)

if MCP_ENABLED:
    INSTALLED_APPS = INSTALLED_APPS + ['rest_framework', 'mcp_server']
    DJANGO_MCP_ENDPOINT = os.environ.get('DJANGO_MCP_ENDPOINT', 'mcp').strip()
    DJANGO_MCP_AUTHENTICATION_CLASSES = [
        'rest_framework.authentication.BasicAuthentication',
    ]
    DJANGO_MCP_GLOBAL_SERVER_CONFIG = {
        'name': os.environ.get(
            'DJANGO_MCP_SERVER_NAME', 'noivas-cia-admin'
        ).strip(),
        'instructions': (
            'Servidor MCP administrativo. Todas as tools exigem admin do '
            'Django. Use list_entities e describe_entity para descobrir '
            'slugs e campos antes de alterar dados.'
        ),
        'stateless': _env_bool('DJANGO_MCP_STATELESS', True),
    }
    # Avoid publishing the package's auxiliary instruction tool. Every tool in
    # this server is declared in core.mcp and enforces _require_admin().
    DJANGO_MCP_GET_SERVER_INSTRUCTIONS_TOOL = False
