# Generated by Django 5.2.15 on 2026-07-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_customer_name_trgm_idx'),
        ('rentals', '0008_rentalitem_proof_photo_filefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('pickup_reminder', 'Aviso de retirada'), ('return_reminder', 'Cobrança de devolução')], max_length=20, verbose_name='tipo')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou')], max_length=10, verbose_name='situação')),
                ('message_id', models.CharField(blank=True, max_length=120, verbose_name='ID da mensagem')),
                ('error', models.TextField(blank=True, verbose_name='erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_messages', to='customers.customer', verbose_name='cliente')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_messages', to='rentals.rental', verbose_name='locação')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'mensagem ao cliente',
                'verbose_name_plural': 'mensagens ao cliente',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['kind', 'status'], name='custmsg_kind_status_idx')],
            },
        ),
    ]
