# Generated by Django 5.2.15 on 2026-07-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('rentals', '0008_rentalitem_proof_photo_filefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_messages', to='rentals.rental', verbose_name='locação'),
        ),
    ]
