# Generated by Django 5.2.15 on 2026-07-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_customermessage_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falhou')], max_length=10, verbose_name='situação'),
        ),
    ]
